app:
  name: Shared base config for default environment
  environment: default
shared:
  config:
    rebate-rate: 9
    minimum-age: 18
spring:
  data:
    mongodb:
      host: ${mongo-host}
      port: ${mongo-port}
      authentication-database: ${mongo-auth-db}
      uri: "mongodb://mongo-username:mongo-password@${mongo-host}:${mongo-port}/$mongo-database?authSource=${mongo-auth-db}"

